--CREATE DATABASE establishment ENCODING = 'UTF-8';

CREATE TABLE USERS(USERNAME VARCHAR(50) PRIMARY KEY, PASSWORD VARCHAR(500) NOT NULL, ENABLED SMALLINT NOT NULL);
CREATE TABLE AUTHORITIES(USERNAME VARCHAR(50) NOT NULL REFERENCES USERS(USERNAME), AUTHORITY VARCHAR(50) NOT NULL);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES('employee', '{bcrypt}$2a$10$CW8ktx3YPpnFQaDXlbDoXOiFlc9CFuNXEn785QqKtqsGr.tDh3zZ.', 1); -- Логин и пароль совпадают
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES('employee', 'ROLE_EMPLOYEE');

CREATE TABLE PASSPORT(PASSPORT_NUMBER VARCHAR(10) PRIMARY KEY, SURNAME VARCHAR(100), NAME VARCHAR(100), PATRONYMIC VARCHAR(100),
                        BIRTH_DATE DATE, BIRTH_PLACE VARCHAR(500), ISSUE_DATE DATE, ISSUE_PLACE VARCHAR(500));

CREATE TABLE SERVICE_REQUESTS(REQUEST_NUMBER SERIAL PRIMARY KEY, CREATE_DATE DATE, SERVICE_NAME VARCHAR(100),
                                PASSPORT_NUMBER VARCHAR(10) REFERENCES PASSPORT(PASSPORT_NUMBER), ACTIVE BOOLEAN);

CREATE TABLE REQUEST_FILES(FILE_ID SERIAL PRIMARY KEY, REQUEST_NUMBER INTEGER REFERENCES SERVICE_REQUESTS(REQUEST_NUMBER),
                            FILE_NAME VARCHAR(100) NOT NULL, FILE_DATA BYTEA NOT NULL);